### ISSUE TITLE
Multipolygone

### ISSUE THREAD

**Issue by StephanGeorg** [jieter/Leaflet.encoded#13]
I try to find a way to encode/decode Multipolygones. Is it possible to do this with Leaflet.encoded?

**Comment by jieter** [comment]
No, not possible.
Can you encode them as a series of Polygons and then after decoding put them back together?

**Comment by StephanGeorg** [comment]
This is what I made so far. But what is the "official" way of doin' it? How does the Google Maps API serve that content? http://jsfiddle.net/doktormolle/9xhsL39u/

**Comment by jieter** [comment]
No idea about how google maps serves this content, that's not really the point of this library. We supply convenience methods for Leaflet.
What would you expect from Leaflet.encoded for you custom SVG implementation?

**Comment by StephanGeorg** [comment]
No, the SVG fiddle was just an example for serving encoded multigones via Google Maps. I'm working on an API and need to serve huge amount of multigones. I'm trying to figure out what the common way is. Thank for your help!

**Comment by jieter** [comment]
Hmm, ok. I've never seen any multipolygons encoded with google's polyline encoding, sorry.
