### ISSUE TITLE
Escape Backslashes

### ISSUE THREAD

**Issue by mtaptich** [jieter/Leaflet.encoded#14]
I completely missed the portion of your ReadME file that warns the user to escape all backslashes. This is an easy fix to manually do, but is it possible to remove all backslashes programmatically? I have been hammering away at this for an embarrassingly long time. I figured that some other users must have come across this before so I figured I'd ask here.  

The polyline that I am working with:
```
_rdfFt}eiVpBUr@jKh@tIDVLXd@fB\hFLdC|@bO@^f@rI\jFJxCB\N~@v@zKnDvi@xF[jBMpMc@~EUxEWjJc@l@IxHc@|@Qn@Qn@Wn@Ud@MbBUrGw@dRaC~Ek@nFu@tAUBnBBfDBxDvChV`AtIdBxNV`Bh@vBr@|BUBkAVLbAf@jE
```

**Comment by jieter** [comment]
I guess by remove you mean escape?

How would you propose to fix this? If you make sure the encoded strings are generated and consumed by your programs and you don't copy/paste these encoded strings around manually you should be fine.
