### ISSUE TITLE
Enhancement : It would be nice to don't use ` " or ' for encoding

### ISSUE THREAD

**Issue by jonathanulco** [jieter/Leaflet.encoded#16]
Hi, 
It would be nice to don't use special caracters like back slash, " or ' for encoding, some langage like GO really don't like ` https://golang.org/ref/spec#String_literals :) 

Thx

**Comment by jieter** [comment]
Yes, but the encoding is defined by google, not by us. We cannot magically remove some characters from the set we encode to.

So unfortunately, we cannot fix this here.
