### ISSUE TITLE
OSRM Precision Changed

### ISSUE THREAD

**Issue by waylonflinn** [jieter/Leaflet.encoded#17]
Thanks for the documentation specifically for OSRM. Just wanted to drop a note that the precision appears to have changed to `5`.

Here's what works for me.
```javascript
var points = L.PolylineUtil.decode(encoded_geometry, 5);
var line = new L.Polyline(points);
line.addTo(map);
```

Tested with the OSRM node module version `5.8.1`.

This also matches the precision used by `leaflet-routing-machine`.
https://github.com/perliedman/leaflet-routing-machine/blob/master/src/osrm-v1.js#L28

**Comment by jieter** [comment]
Fixed with 4ed19d9
