### ISSUE TITLE
BUG: error in implementation of encoding algorithm

### ISSUE THREAD

**Issue by MaRaSu** [jieter/Leaflet.encoded#18]
Noticed an error when encoded-decoded back an GPX-track with coordinates having 8 decimal places. Decoded track was increasingly off from the original track. Reason was the same as described in https://stackoverflow.com/questions/39247286/polyline-encode-gets-wrong-lat-lng-after-decoding.

Fix was to modify in `encodeDeltas` function line
`var num = numbers[i];` to
`var num = numbers[i].toFixed(options.precision);`

Did not do a PR since not sure if this repo is still actively maintained.

**Comment by jieter** [comment]
Not super-active, but every now and then I'll look around here.

A PR would be nice, preferably including a test.

**Comment by wcauchois** [comment]
I'm considering using this library. Is this PR going to get merged anytime soon?

And as an aside, is this still the best library for performing the google polyline encoding in NodeJS on the server? Or is there another more active library?

**Comment by MaRaSu** [comment]
This library indeed looks not be maintained anymore.

[@mapbox/polyline](https://www.npmjs.com/package/@mapbox/polyline) seems to be pretty popular, however I have not tested it.

**Comment by jieter** [comment]
@wcauchois merged and released [0.0.9](https://www.npmjs.com/package/polyline-encoded/v/0.0.9)
